package ch.davide.pham.battleshipproject.ui

/*
 * Author: Davide Pham (individual FHNW student project).
 * Simple in-app localization keeps the project aligned with the course material.
 * Updated to match official server terminology and requirements.
 */
enum class AppLanguage(val code: String, val displayName: String) {
    ENGLISH("EN", "English"),
    ITALIAN("IT", "Italiano"),
    FRENCH("FR", "Francais"),
    GERMAN("DE", "Deutsch")
}

data class AppStrings(
    val fleetCommand: String,
    val battleship: String,
    val homeTagline: String,
    val enterBattle: String,
    val settings: String,
    val howToPlay: String,
    val about: String,
    val backToMenu: String,
    val joinTitle: String,
    val joinSubtitle: String,
    val playerName: String,
    val gameKey: String,
    val minimumThree: String,
    val shareKey: String,
    val pingServer: String,
    val createGame: String,
    val joinGame: String,
    val configureFleet: String,
    val serverOnline: String,
    val serverOffline: String,
    val checkingServer: String,
    val language: String,
    val soundEffects: String,
    val backgroundMusic: String,
    val settingsNote: String,
    val howIntro: String,
    val howStepOne: String,
    val howStepTwo: String,
    val howStepThree: String,
    val howStepFour: String,
    val howStepFive: String,
    val aboutDescription: String,
    val technologies: String,
    val fleetDeployment: String,
    val positionFleet: String,
    val positionHelp: String,
    val rotateVertical: String,
    val rotateHorizontal: String,
    val randomize: String,
    val deployFleet: String,
    val onlineJoinHelp: String,
    val cancelConnection: String,
    val battleTitle: String,
    val targetingGrid: String,
    val targetHint: String,
    val friendlyGrid: String,
    val incomingFire: String,
    val salvos: String,
    val accuracy: String,
    val enemySunk: String,
    val friendlyFleet: String,
    val enemyFleet: String,
    val pause: String,
    val resume: String,
    val quitBattle: String,
    val reconnect: String,
    val weaponsFree: String,
    val connectingTitle: String,
    val connectingMessage: String,
    val yourTurn: String,
    val yourTurnMessage: String,
    val waitingEnemy: String,
    val waitingEnemyMessage: String,
    val miss: String,
    val hit: String,
    val selectedVessel: String,
    val pausedTitle: String,
    val pausedMessage: String,
    val victory: String,
    val defeat: String,
    val victoryMessage: String,
    val defeatMessage: String,
    val playAgain: String,
    val returnHome: String,
    val leaveTitle: String,
    val leaveMessage: String,
    val leaveBattle: String,
    val stay: String,
    val commandNotice: String,
    val understood: String,
    val playerKeyError: String,
    val repeatedTarget: String,
    val invalidPosition: String
)

val AppLanguage.strings: AppStrings
    get() = when (this) {
        AppLanguage.ENGLISH -> AppStrings(
            fleetCommand = "FLEET COMMAND",
            battleship = "BATTLESHIP",
            homeTagline = "Command the ocean. Read the grid. Sink the enemy fleet.",
            enterBattle = "ENTER BATTLE",
            settings = "SETTINGS",
            howToPlay = "HOW TO PLAY",
            about = "ABOUT",
            backToMenu = "MENU",
            joinTitle = "OPEN BATTLE CHANNEL",
            joinSubtitle = "Two commanders, one shared game key.",
            playerName = "Commander name",
            gameKey = "Game key",
            minimumThree = "At least 3 characters",
            shareKey = "Use exactly the same key on both devices",
            pingServer = "PING SERVER",
            createGame = "CONFIGURE HOST FLEET",
            joinGame = "CONFIGURE JOIN FLEET",
            configureFleet = "CONFIGURE FLEET",
            serverOnline = "Server connected",
            serverOffline = "Server not reachable",
            checkingServer = "CHECKING SERVER",
            language = "LANGUAGE",
            soundEffects = "SOUND EFFECTS",
            backgroundMusic = "BACKGROUND MUSIC",
            settingsNote = "Audio controls are prepared for future sound assets.",
            howIntro = "Sink all five enemy ships before your own fleet is destroyed.",
            howStepOne = "1. Both players enter different names and the same game key.",
            howStepTwo = "2. Position the five ships without overlaps or cells outside the grid.",
            howStepThree = "3. When it is your turn, tap one enemy coordinate from A1 to J10.",
            howStepFour = "4. Red markers are hits, cyan rings are misses and sunk ships are listed.",
            howStepFive = "5. After firing, wait for the enemy move. The server may take some time.",
            aboutDescription = "An FHNW Android client for the official Battleship REST server.",
            technologies = "Kotlin, Jetpack Compose, Canvas, ViewModel, Retrofit and OkHttp.",
            fleetDeployment = "Fleet deployment",
            positionFleet = "Position your fleet",
            positionHelp = "Select a vessel, choose its orientation and tap its bow position.",
            rotateVertical = "ROTATE VERTICAL",
            rotateHorizontal = "ROTATE HORIZONTAL",
            randomize = "RANDOMIZE",
            deployFleet = "CONNECT TO ONLINE GAME",
            onlineJoinHelp = "Connect to the official server via POST /game/join. No offline gameplay is supported.",
            cancelConnection = "CANCEL CONNECTION",
            battleTitle = "Fleet Command",
            targetingGrid = "TARGETING GRID",
            targetHint = "Tap an unmarked sector to fire",
            friendlyGrid = "FRIENDLY GRID",
            incomingFire = "Incoming enemy fire",
            salvos = "SALVOS",
            accuracy = "ACCURACY",
            enemySunk = "ENEMY SUNK",
            friendlyFleet = "FRIENDLY FLEET",
            enemyFleet = "ENEMY FLEET",
            pause = "PAUSE",
            resume = "RESUME",
            quitBattle = "QUIT BATTLE",
            reconnect = "RECONNECT",
            weaponsFree = "WEAPONS FREE",
            connectingTitle = "Waiting for opponent...",
            connectingMessage = "Connecting to the server. If you are the first player, this screen will stay active until the second commander joins and launches a salvo.",
            yourTurn = "YOUR TURN",
            yourTurnMessage = "Select an unmarked sector and launch a salvo.",
            waitingEnemy = "ENEMY TURN",
            waitingEnemyMessage = "Sonar is listening for the opponent's salvo.",
            miss = "MISS",
            hit = "HIT",
            selectedVessel = "SELECTED VESSEL",
            pausedTitle = "BATTLE PAUSED",
            pausedMessage = "Your controls are paused. The online server session remains active.",
            victory = "YOU WON!",
            defeat = "YOU LOST!",
            victoryMessage = "You sank the entire enemy fleet.",
            defeatMessage = "The opponent sank your entire fleet.",
            playAgain = "PLAY AGAIN",
            returnHome = "EXIT TO HOME",
            leaveTitle = "Leave this battle?",
            leaveMessage = "The server has no leave command. This game key may remain occupied until the inactive game is removed.",
            leaveBattle = "LEAVE BATTLE",
            stay = "STAY",
            commandNotice = "Command notice",
            understood = "UNDERSTOOD",
            playerKeyError = "Player name and game key must each contain at least 3 characters.",
            repeatedTarget = "This coordinate has already been targeted.",
            invalidPosition = "Invalid position: ships cannot overlap or leave the grid."
        )

        AppLanguage.ITALIAN -> AppStrings(
            fleetCommand = "COMANDO FLOTTA",
            battleship = "BATTAGLIA NAVALE",
            homeTagline = "Comanda l'oceano. Leggi la griglia. Affonda la flotta nemica.",
            enterBattle = "ENTRA IN BATTAGLIA",
            settings = "IMPOSTAZIONI",
            howToPlay = "COME GIOCARE",
            about = "INFORMAZIONI",
            backToMenu = "MENU",
            joinTitle = "APRI IL CANALE DI BATTAGLIA",
            joinSubtitle = "Due comandanti, una stessa chiave di partita.",
            playerName = "Nome comandante",
            gameKey = "Chiave partita",
            minimumThree = "Almeno 3 caratteri",
            shareKey = "Usa esattamente la stessa chiave su entrambi i dispositivi",
            pingServer = "CONTROLLA SERVER",
            createGame = "CONFIGURA FLOTTA HOST",
            joinGame = "CONFIGURA FLOTTA JOIN",
            configureFleet = "CONFIGURA FLOTTA",
            serverOnline = "Server connesso",
            serverOffline = "Server non raggiungibile",
            checkingServer = "CONTROLLO SERVER",
            language = "LINGUA",
            soundEffects = "EFFETTI SONORI",
            backgroundMusic = "MUSICA",
            settingsNote = "I controlli audio sono pronti per eventuali suoni futuri.",
            howIntro = "Affonda tutte le cinque navi nemiche prima che la tua flotta venga distrutta.",
            howStepOne = "1. I giocatori inseriscono nomi diversi e la stessa chiave di partita.",
            howStepTwo = "2. Posiziona le cinque navi senza sovrapposizioni e dentro la griglia.",
            howStepThree = "3. Durante il tuo turno tocca una coordinata nemica da A1 a J10.",
            howStepFour = "4. Il rosso indica un colpo, il cerchio azzurro un colpo mancato.",
            howStepFive = "5. Dopo lo sparo attendi il nemico. La risposta del server puo richiedere tempo.",
            aboutDescription = "Client Android FHNW per il server REST ufficiale di Battleship.",
            technologies = "Kotlin, Jetpack Compose, Canvas, ViewModel, Retrofit e OkHttp.",
            fleetDeployment = "Schieramento flotta",
            positionFleet = "Posiziona la flotta",
            positionHelp = "Seleziona una nave, scegli l'orientamento e tocca la posizione della prua.",
            rotateVertical = "RUOTA VERTICALE",
            rotateHorizontal = "RUOTA ORIZZONTALE",
            randomize = "CASUALE",
            deployFleet = "CONNETTITI ALLA PARTITA ONLINE",
            onlineJoinHelp = "Connessione al server ufficiale tramite POST /game/join. Nessuna modalità offline supportata.",
            cancelConnection = "ANNULLA CONNESSIONE",
            battleTitle = "Comando Flotta",
            targetingGrid = "GRIGLIA NEMICA",
            targetHint = "Tocca un settore libero per sparare",
            friendlyGrid = "GRIGLIA AMICA",
            incomingFire = "Colpi nemici ricevuti",
            salvos = "COLPI",
            accuracy = "PRECISIONE",
            enemySunk = "NAVI AFFONDATE",
            friendlyFleet = "FLOTTA AMICA",
            enemyFleet = "FLOTTA NEMICA",
            pause = "PAUSA",
            resume = "RIPRENDI",
            quitBattle = "ABBANDONA",
            reconnect = "RICONNETTI",
            weaponsFree = "FUOCO LIBERO",
            connectingTitle = "In attesa dell'avversario...",
            connectingMessage = "Connessione al server. Se sei il primo giocatore, questa schermata rimarrà attiva finché il secondo comandante non si unirà e lancerà un colpo.",
            yourTurn = "IL TUO TURNO",
            yourTurnMessage = "Seleziona un settore libero e lancia un colpo.",
            waitingEnemy = "TURNO NEMICO",
            waitingEnemyMessage = "Il sonar e in ascolto del colpo avversario.",
            miss = "MANCATO",
            hit = "COLPITO",
            selectedVessel = "NAVE SELEZIONATA",
            pausedTitle = "BATTAGLIA IN PAUSA",
            pausedMessage = "I comandi sono in pausa. La sessione online rimane attiva.",
            victory = "HAI VINTO!",
            defeat = "HAI PERSO!",
            victoryMessage = "Hai affondato tutta la flotta nemica.",
            defeatMessage = "L'avversario ha affondato tutta la tua flotta.",
            playAgain = "GIOCA ANCORA",
            returnHome = "TORNA AL MENU",
            leaveTitle = "Abbandonare la battaglia?",
            leaveMessage = "Il server non dispone di un comando di uscita. La chiave puo restare occupata finche la partita inattiva viene rimossa.",
            leaveBattle = "ABBANDONA",
            stay = "RESTA",
            commandNotice = "Avviso di comando",
            understood = "HO CAPITO",
            playerKeyError = "Nome e chiave della partita devono contenere almeno 3 caratteri.",
            repeatedTarget = "Questa coordinata e gia stata colpita.",
            invalidPosition = "Posizione non valida: le navi non possono sovrapporsi o uscire dalla griglia."
        )

        AppLanguage.FRENCH -> AppStrings(
            fleetCommand = "COMMANDE DE FLOTTE",
            battleship = "BATAILLE NAVALE",
            homeTagline = "Commandez l'ocean. Lisez la grille. Coulez la flotte ennemie.",
            enterBattle = "ENTRER EN BATAILLE",
            settings = "PARAMETRES",
            howToPlay = "COMMENT JOUER",
            about = "A PROPOS",
            backToMenu = "MENU",
            joinTitle = "OUVRIR LE CANAL DE COMBAT",
            joinSubtitle = "Deux commandants, une meme cle de partie.",
            playerName = "Nom du commandant",
            gameKey = "Cle de partie",
            minimumThree = "Au moins 3 caracteres",
            shareKey = "Utilisez exactement la meme cle sur les deux appareils",
            pingServer = "TESTER LE SERVEUR",
            createGame = "CONFIGURER FLOTTE HOTE",
            joinGame = "CONFIGURER FLOTTE JOIN",
            configureFleet = "CONFIGURER LA FLOTTE",
            serverOnline = "Serveur connecte",
            serverOffline = "Serveur non joignable",
            checkingServer = "TEST DU SERVEUR",
            language = "LANGUE",
            soundEffects = "EFFETS SONORES",
            backgroundMusic = "MUSIQUE",
            settingsNote = "Les commandes audio sont pretes pour de futurs sons.",
            howIntro = "Coulez les cinq navires ennemis avant la destruction de votre flotte.",
            howStepOne = "1. Les joueurs saisissent des noms differents et la meme cle.",
            howStepTwo = "2. Placez les cinq navires sans chevauchement et dans la grille.",
            howStepThree = "3. Pendant votre tour, touchez une coordonnee de A1 a J10.",
            howStepFour = "4. Le rouge indique une touche et le cercle cyan un tir manque.",
            howStepFive = "5. Apres le tir, attendez l'adversaire. Le serveur peut prendre du temps.",
            aboutDescription = "Client Android FHNW pour le server REST officiel Battleship.",
            technologies = "Kotlin, Jetpack Compose, Canvas, ViewModel, Retrofit et OkHttp.",
            fleetDeployment = "Deploiement de la flotte",
            positionFleet = "Placez votre flotte",
            positionHelp = "Selectionnez un navire, son orientation et touchez la position de la proue.",
            rotateVertical = "PIVOTER VERTICAL",
            rotateHorizontal = "PIVOTER HORIZONTAL",
            randomize = "ALEATOIRE",
            deployFleet = "CONNEXION A LA PARTIE EN LIGNE",
            onlineJoinHelp = "Connexion au serveur officiel via POST /game/join. Pas de mode hors ligne.",
            cancelConnection = "ANNULER",
            battleTitle = "Commande de Flotte",
            targetingGrid = "GRILLE ENNEMIE",
            targetHint = "Touchez une case libre pour tirer",
            friendlyGrid = "GRILLE ALLIEE",
            incomingFire = "Tirs ennemis recus",
            salvos = "TIRS",
            accuracy = "PRECISION",
            enemySunk = "ENNEMIS COULES",
            friendlyFleet = "FLOTTE ALLIEE",
            enemyFleet = "FLOTTE ENNEMIE",
            pause = "PAUSE",
            resume = "REPRENDRE",
            quitBattle = "QUITTER",
            reconnect = "RECONNECTER",
            weaponsFree = "FEU LIBRE",
            connectingTitle = "En attente de l'adversaire...",
            connectingMessage = "Connexion au serveur. Si vous êtes le premier joueur, cet écran restera actif jusqu'à ce que le second commandant rejoigne et lance une salve.",
            yourTurn = "A VOTRE TOUR",
            yourTurnMessage = "Selectionnez une case libre et lancez une salve.",
            waitingEnemy = "TOUR ENNEMI",
            waitingEnemyMessage = "Le sonar attend la salve de l'adversaire.",
            miss = "MANQUE",
            hit = "TOUCHE",
            selectedVessel = "NAVIRE SELECTIONNE",
            pausedTitle = "BATAILLE EN PAUSE",
            pausedMessage = "Les commandes sont en pause. La session en ligne reste active.",
            victory = "VICTOIRE!",
            defeat = "DEFAITE!",
            victoryMessage = "Vous avez coule toute la flotte ennemie.",
            defeatMessage = "L'adversaire a coule toute votre flotte.",
            playAgain = "REJOUER",
            returnHome = "RETOUR AU MENU",
            leaveTitle = "Quitter cette bataille?",
            leaveMessage = "Le serveur ne dispose pas de commande de sortie. La cle peut rester occupee jusqu'a la suppression de la partie inactive.",
            leaveBattle = "QUITTER",
            stay = "RESTER",
            commandNotice = "Message de commande",
            understood = "COMPRIS",
            playerKeyError = "Le nom et la cle doivent contenir au moins 3 caracteres.",
            repeatedTarget = "Cette coordonnee a deja ete visee.",
            invalidPosition = "Position invalide: les navires ne peuvent pas se chevaucher ou sortir de la grille."
        )

        AppLanguage.GERMAN -> AppStrings(
            fleetCommand = "FLOTTENKOMMANDO",
            battleship = "SCHIFFE VERSENKEN",
            homeTagline = "Beherrsche den Ozean. Lies das Raster. Versenke die feindliche Flotte.",
            enterBattle = "SCHLACHT STARTEN",
            settings = "EINSTELLUNGEN",
            howToPlay = "SPIELANLEITUNG",
            about = "UBER DAS PROJEKT",
            backToMenu = "MENU",
            joinTitle = "GEFECHTSKANAL OFFNEN",
            joinSubtitle = "Zwei Kommandanten, derselbe Spielschlussel.",
            playerName = "Name des Kommandanten",
            gameKey = "Spielschlussel",
            minimumThree = "Mindestens 3 Zeichen",
            shareKey = "Auf beiden Geraten exakt denselben Schlussel verwenden",
            pingServer = "SERVER TESTEN",
            createGame = "HOST-FLOTTE KONFIGURIEREN",
            joinGame = "JOIN-FLOTTE KONFIGURIEREN",
            configureFleet = "FLOTTE KONFIGURIEREN",
            serverOnline = "Server verbunden",
            serverOffline = "Server nicht erreichbar",
            checkingServer = "SERVER WIRD GEPRUFT",
            language = "SPRACHE",
            soundEffects = "SOUNDEFFEKTE",
            backgroundMusic = "HINTERGRUNDMUSIK",
            settingsNote = "Die Audiosteuerung ist fur spatere Sounds vorbereitet.",
            howIntro = "Versenke alle funf feindlichen Schiffe, bevor deine Flotte zerstort wird.",
            howStepOne = "1. Beide Spieler verwenden verschiedene Namen und denselben Spielschlussel.",
            howStepTwo = "2. Platziere funf Schiffe ohne Uberlappung innerhalb des Rasters.",
            howStepThree = "3. Tippe in deinem Zug auf eine Koordinate von A1 bis J10.",
            howStepFour = "4. Rot bedeutet Treffer, ein cyanfarbener Ring bedeutet Fehlschuss.",
            howStepFive = "5. Warte nach dem Schuss auf den Gegner. Der Server kann Zeit benotigen.",
            aboutDescription = "FHNW Android-Client fur den offiziellen Battleship REST-Server.",
            technologies = "Kotlin, Jetpack Compose, Canvas, ViewModel, Retrofit und OkHttp.",
            fleetDeployment = "Flotte aufstellen",
            positionFleet = "Flotte positionieren",
            positionHelp = "Wahle ein Schiff, die Ausrichtung und tippe auf die Bugposition.",
            rotateVertical = "VERTIKAL DREHEN",
            rotateHorizontal = "HORIZONTAL DREHEN",
            randomize = "ZUFALLIG",
            deployFleet = "MIT ONLINE-SPIEL VERBINDEN",
            onlineJoinHelp = "Verbindung zum offiziellen Server über POST /game/join. Kein Offline-Modus.",
            cancelConnection = "VERBINDUNG ABBRECHEN",
            battleTitle = "Flottenkommando",
            targetingGrid = "ZIELRASTER",
            targetHint = "Auf ein freies Feld tippen und feuern",
            friendlyGrid = "EIGENES RASTER",
            incomingFire = "Eingegangene Feindschusse",
            salvos = "SCHUSSE",
            accuracy = "GENAUIGKEIT",
            enemySunk = "VERSENKT",
            friendlyFleet = "EIGENE FLOTTE",
            enemyFleet = "FEINDLICHE FLOTTE",
            pause = "PAUSE",
            resume = "FORTSETZEN",
            quitBattle = "SCHLACHT VERLASSEN",
            reconnect = "NEU VERBINDEN",
            weaponsFree = "FEUER FREI",
            connectingTitle = "Warten auf Gegner...",
            connectingMessage = "Verbindung zum Server. Wenn Sie der erste Spieler sind, bleibt dieser Bildschirm aktiv, bis der zweite Kommandant beitritt und eine Salve abfeuert.",
            yourTurn = "DEIN ZUG",
            yourTurnMessage = "Wahle ein freies Feld und feuere.",
            waitingEnemy = "GEGNER AM ZUG",
            waitingEnemyMessage = "Das Sonar wartet auf den gegnerischen Schuss.",
            miss = "DANEBEN",
            hit = "TREFFER",
            selectedVessel = "GEWAHLTES SCHIFF",
            pausedTitle = "SCHLACHT PAUSIERT",
            pausedMessage = "Die Steuerung ist pausiert. Die Online-Sitzung bleibt aktiv.",
            victory = "GEWONNEN!",
            defeat = "VERLOREN!",
            victoryMessage = "Du hast die gesamte feindliche Flotte versenkt.",
            defeatMessage = "Der Gegner hat deine gesamte Flotte versenkt.",
            playAgain = "NOCH EINMAL",
            returnHome = "ZURUCK ZUM MENU",
            leaveTitle = "Schlacht verlassen?",
            leaveMessage = "Der Server hat keinen Ausgangsbefehl. Der Schlussel kann bis zur Loschung des inaktiven Spiels belegt bleiben.",
            leaveBattle = "VERLASSEN",
            stay = "BLEIBEN",
            commandNotice = "Kommandohinweis",
            understood = "VERSTANDEN",
            playerKeyError = "Name und Spielschlussel mussen mindestens 3 Zeichen enthalten.",
            repeatedTarget = "Diese Koordinate wurde bereits beschossen.",
            invalidPosition = "Ungultige Position: Schiffe durfen sich nicht uberlappen oder das Raster verlassen."
        )
    }
